name: ingfo_movies
description: "A Movies Information Flutter App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # * Toast
  fluttertoast: ^8.2.4

  # * Network Connectivity Check
  connectivity_plus: ^5.0.2

  # * APIs
  retrofit: ^4.1.0
  http: ^1.2.0
  dio: ^5.4.0

  # * Adds JSON Annotation For Generating JSON Maps
  json_annotation: ^4.8.1

  # * Local Database
  floor: ^1.4.2

  # * Provider
  provider: ^6.1.1

  # * BLoC
  flutter_bloc: ^8.1.4

  # * Dependency Injection
  get_it: ^7.6.7

  # * Load Image URL
  cached_network_image: ^3.3.1

  # * Set Fonts From Google Fonts
  google_fonts: ^6.1.0

  # * Simple Persistent Storage
  shared_preferences: ^2.2.2

  # * Simple Object Comparison
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
